# Generated by Django 4.2.13 on 2026-05-28 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('flag', 'Flagged'), ('edit', 'Edited')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('diff', models.JSONField(blank=True, null=True)),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.normalizedemission')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
