# Generated by Django 4.2.13 on 2026-05-28 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('source', models.CharField(max_length=20)),
                ('activity_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('original_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('original_unit', models.CharField(max_length=50)),
                ('normalized_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('flag_reason', models.TextField(blank=True, default='')),
                ('manually_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='ingestion.ingestionbatch')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_emissions', to=settings.AUTH_USER_MODEL)),
                ('raw_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission', to='ingestion.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='tenants.tenant')),
            ],
        ),
    ]
